stackdio/api/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from collections import OrderedDict

from django.conf.urls import include, url
from django.views.defaults import page_not_found, server_error, bad_request, permission_denied
from rest_framework import permissions, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.views import APIView


class APIRootView(APIView):
    """
    Root of the stackd.io API. Below are all of the API endpoints that
    are currently accessible. Each API will have its own documentation
    and particular parameters that may discoverable by browsing directly
    to them.
    """

    def get(self, request, format=None):
        api = OrderedDict((
            ('version', reverse('stackdio:version',
                                request=request,
                                format=format)),
            ('events', reverse('stackdio:event-list',
                               request=request,
                               format=format)),
            ('notifications', reverse('stackdio:notifications:root',
                                      request=request,
                                      format=format)),
            ('users', reverse('api:users:user-list',
                              request=request,
                              format=format)),
            ('groups', reverse('api:users:group-list',
                               request=request,
                               format=format)),
            ('current_user', reverse('api:users:currentuser-detail',
                                     request=request,
                                     format=format)),
            ('cloud', reverse('api:cloud:root',
                              request=request,
                              format=format)),
            ('blueprints', reverse('api:blueprints:blueprint-list',
                                   request=request,
                                   format=format)),
            ('formulas', reverse('api:formulas:formula-list',
                                 request=request,
                                 format=format)),
            ('stacks', reverse('api:stacks:stack-list',
                               request=request,
                               format=format)),
            ('environments', reverse('api:environments:environment-list',
                                     request=request,
                                     format=format)),
            ('volumes', reverse('api:volumes:volume-list',
                                request=request,
                                format=format)),
            ('search', reverse('api:search:search',
                               request=request,
                               format=format)),
        ))

        return Response(api)


@api_view(APIView.http_method_names)
@permission_classes([permissions.AllowAny])
def api_bad_request_view(request, *args, **kwargs):
    return Response({'detail': 'Bad request.'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(APIView.http_method_names)
@permission_classes([permissions.AllowAny])
def api_permission_denied_view(request, *args, **kwargs):
    return Response({'detail': 'Permission denied.'}, status=status.HTTP_403_FORBIDDEN)


@api_view(APIView.http_method_names)
@permission_classes([permissions.AllowAny])
def api_not_found_view(request, *args, **kwargs):
    return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)


@api_view(APIView.http_method_names)
@permission_classes([permissions.AllowAny])
def api_server_error_view(request, *args, **kwargs):
    return Response({'detail': 'Internal server error.'},
                    status=status.HTTP_500_INTERNAL_SERVER_ERROR)


ERROR_MAP = {
    400: {
        'api': api_bad_request_view,
        'default': bad_request,
    },
    403: {
        'api': api_permission_denied_view,
        'default': permission_denied,
    },
    404: {
        'api': api_not_found_view,
        'default': page_not_found,
    },
    500: {
        'api': api_server_error_view,
        'default': server_error,
    },
}


def get_error_handler(error_code):

    # This is our custom error handler so that 400/403/404/500 requests to /api endpoints
    # return JSON instead of the default page
    def error_handler(request, *args, **kwargs):
        if request.path.startswith('/api'):
            ret = ERROR_MAP[error_code]['api'](request, *args, **kwargs)
            ret.render()
            return ret
        else:
            # Just use the default one
            return ERROR_MAP[error_code]['default'](request, *args, **kwargs)

    return error_handler


urlpatterns = (
    url(r'^$', APIRootView.as_view(), name='root'),

    ##
    # IMPORTS URLS FROM ALL APPS
    ##
    url(r'^cloud/', include('stackdio.api.cloud.urls', namespace='cloud')),
    url(r'^blueprints/', include('stackdio.api.blueprints.urls', namespace='blueprints')),
    url(r'^formulas/', include('stackdio.api.formulas.urls', namespace='formulas')),
    url(r'^stacks/', include('stackdio.api.stacks.urls', namespace='stacks')),
    url(r'^environments/', include('stackdio.api.environments.urls', namespace='environments')),
    url(r'^volumes/', include('stackdio.api.volumes.urls', namespace='volumes')),
    url(r'^search/', include('stackdio.api.search.urls', namespace='search')),
    url(r'^', include('stackdio.api.users.urls', namespace='users')),
)

# Format suffixes - this only should go on API endpoints, not everything!
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

stackdio/core/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import include, url
from stackdio.core import api

urlpatterns = (
    url(r'^api/version/$',
        api.VersionAPIView.as_view(),
        name='version'),

    url(r'^api/events/$',
        api.EventListAPIView.as_view(),
        name='event-list'),

    url(r'^api/notifications/',
        include('stackdio.core.notifications.urls', namespace='notifications')),
)

stackdio/server/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
stackdio URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from stackdio.api.urls import get_error_handler

# Enable admin interface
admin.autodiscover()

urlpatterns = (
    # Grab the core URLs.  Basically just the version endpoint.
    url(r'^', include('stackdio.core.urls', namespace='stackdio')),

    # API v1 root endpoint -- add additional URLs to urls.py in the api module.
    url(r'^api/', include('stackdio.api.urls', namespace='api')),

    # Default login/logout views. Without this you won't get the login/logout links
    # in the browsable api.
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),

    # Grab the ui URLs.  Stuff like index, login, logout, etc
    url(r'^', include('stackdio.ui.urls', namespace='ui')),

    # Admin interface
    url(r'^__private/admin/', include(admin.site.urls)),
)

# Override the default handlers
handler400 = get_error_handler(400)
handler403 = get_error_handler(403)
handler404 = get_error_handler(404)
handler500 = get_error_handler(500)

stackdio/ui/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from stackdio.core.utils import cached_url
from stackdio.ui import views
from stackdio.ui.views import accounts
from stackdio.ui.views import blueprints
from stackdio.ui.views import environments
from stackdio.ui.views import formulas
from stackdio.ui.views import images
from stackdio.ui.views import snapshots
from stackdio.ui.views import stacks
from stackdio.ui.views import users

auth_login_kwargs = {
    'template_name': 'stackdio/login.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_confirm_kwargs = {
    'post_reset_redirect': 'ui:password_reset_complete',
    'template_name': 'stackdio/auth/password_reset_confirm.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_complete_kwargs = {
    'template_name': 'stackdio/auth/password_reset_complete.html',
    'extra_context': {'hide_navbar': True},
}

urlpatterns = (
    cached_url(r'^$',
               views.RootView.as_view(),
               name='index'),

    cached_url(r'^login/$',
               auth_views.login,
               auth_login_kwargs,
               name='login',
               user_sensitive=False),

    url(r'^logout/$',
        auth_views.logout_then_login,
        name='logout'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        auth_reset_confirm_kwargs,
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        auth_reset_complete_kwargs,
        name='password_reset_complete'),

    cached_url(r'^js/main.js$',
               views.AppMainView.as_view(),
               name='js-main',
               user_sensitive=False),

    cached_url('^user/$',
               users.UserProfileView.as_view(),
               name='user-profile',
               timeout=10),

    cached_url('^user/password/$',
               users.UserPasswordChangeView.as_view(),
               name='user-password-change',
               timeout=10),

    cached_url(r'^users/$',
               users.UserListView.as_view(),
               name='user-list',
               timeout=30),

    cached_url(r'^users/create/$',
               users.UserCreateView.as_view(),
               name='user-create'),

    cached_url(r'^users/permissions/$',
               users.UserModelPermissionsView.as_view(),
               name='user-model-permissions'),

    cached_url(r'^groups/$',
               users.GroupListView.as_view(),
               name='group-list',
               timeout=30),

    cached_url(r'^groups/create/$',
               users.GroupCreateView.as_view(),
               name='group-create'),

    cached_url(r'^groups/permissions/$',
               users.GroupModelPermissionsView.as_view(),
               name='group-model-permissions'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/$',
               users.GroupDetailView.as_view(),
               name='group-detail',
               timeout=30),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/members/$',
               users.GroupMembersView.as_view(),
               name='group-members'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/permissions/$',
               users.GroupObjectPermissionsView.as_view(),
               name='group-object-permissions'),

    cached_url(r'^stacks/$',
               stacks.StackListView.as_view(),
               name='stack-list',
               timeout=30),

    cached_url(r'^stacks/create/$',
               stacks.StackCreateView.as_view(),
               name='stack-create'),

    cached_url(r'^stacks/permissions/$',
               stacks.StackModelPermissionsView.as_view(),
               name='stack-model-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/$',
               stacks.StackDetailView.as_view(),
               name='stack-detail',
               timeout=30),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/properties/$',
               stacks.StackPropertiesView.as_view(),
               name='stack-properties'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/labels/$',
               stacks.StackLabelsView.as_view(),
               name='stack-labels'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/hosts/$',
               stacks.StackHostsView.as_view(),
               name='stack-hosts'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/components/$',
               stacks.StackComponentsView.as_view(),
               name='stack-components'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/volumes/$',
               stacks.StackVolumesView.as_view(),
               name='stack-volumes'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/$',
               stacks.StackCommandsView.as_view(),
               name='stack-commands'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/(?P<command_pk>[0-9]+)/$',
               stacks.StackCommandDetailView.as_view(),
               name='stack-command-detail'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/access_rules/$',
               stacks.StackAccessRulesView.as_view(),
               name='stack-access-rules'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/formula_versions/$',
               stacks.StackFormulaVersionsView.as_view(),
               name='stack-formula-versions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/permissions/$',
               stacks.StackObjectPermissionsView.as_view(),
               name='stack-object-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/logs/$',
               stacks.StackLogsView.as_view(),
               name='stack-logs'),

    cached_url(r'^environments/$',
               environments.EnvironmentListView.as_view(),
               name='environment-list',
               timeout=30),

    cached_url(r'^environments/create/$',
               environments.EnvironmentCreateView.as_view(),
               name='environment-create'),

    cached_url(r'^environments/permissions/$',
               environments.EnvironmentModelPermissionsView.as_view(),
               name='environment-model-permissions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/$',
               environments.EnvironmentDetailView.as_view(),
               name='environment-detail',
               timeout=30),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/properties/$',
               environments.EnvironmentPropertiesView.as_view(),
               name='environment-properties'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/hosts/$',
               environments.EnvironmentHostsView.as_view(),
               name='environment-hosts'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/labels/$',
               environments.EnvironmentLabelsView.as_view(),
               name='environment-labels'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/formula_versions/$',
               environments.EnvironmentFormulaVersionsView.as_view(),
               name='environment-formula-versions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/components/$',
               environments.EnvironmentComponentsView.as_view(),
               name='environment-components'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/logs/$',
               environments.EnvironmentLogsView.as_view(),
               name='environment-logs'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/permissions/$',
               environments.EnvironmentObjectPermissionsView.as_view(),
               name='environment-object-permissions'),

    cached_url(r'^blueprints/$',
               blueprints.BlueprintListView.as_view(),
               name='blueprint-list',
               timeout=30),

    cached_url(r'^blueprints/permissions/$',
               blueprints.BlueprintModelPermissionsView.as_view(),
               name='blueprint-model-permissions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/$',
               blueprints.BlueprintDetailView.as_view(),
               name='blueprint-detail',
               timeout=30),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/properties/$',
               blueprints.BlueprintPropertiesView.as_view(),
               name='blueprint-properties'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/labels/$',
               blueprints.BlueprintLabelsView.as_view(),
               name='blueprint-labels'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/host_definitions/$',
               blueprints.BlueprintHostDefinitionsView.as_view(),
               name='blueprint-host-definitions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/formula_versions/$',
               blueprints.BlueprintFormulaVersionsView.as_view(),
               name='blueprint-formula-versions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/permissions/$',
               blueprints.BlueprintObjectPermissionsView.as_view(),
               name='blueprint-object-permissions'),

    cached_url(r'^formulas/$',
               formulas.FormulaListView.as_view(),
               name='formula-list',
               timeout=30),

    cached_url(r'^formulas/import/$',
               formulas.FormulaImportView.as_view(),
               name='formula-import'),

    cached_url(r'^formulas/permissions/$',
               formulas.FormulaModelPermissionsView.as_view(),
               name='formula-model-permissions'),

stackdio/core/templates/stackdio/base.html
{% load staticfiles %}
{% load stackdio %}
<!DOCTYPE html>
<html lang="en">
<!--
	Copyright 2017,  Digital Reasoning

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>stackd.io | {{ title }}</title>
    <meta name="description" content="{{ description }}">

    <meta property="og:type" content="object">
    <meta property="og:url" content="/">
    <meta property="og:site_name" content="stackd.io">
    <meta property="og:title" content="{{ title }}">
    <meta property="og:description" content="{{ description }}">

    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@stackdio">
    <meta name="twitter:title" content="{{ title }}">
    <meta name="twitter:description" content="{{ description }}">
    {% include 'stackdio/favicons.html' %}

    {% if not user_agent_only %}
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,600,300">
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/fuelux/dist/css/fuelux.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/css/stackdio.css' %}">

    <!-- extra stylesheets -->
    {% block stylesheets %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endif %}
</head>
<body class="fuelux">
{% if not user_agent_only %}
{% block body %}
    {% block navbar %}
        <nav class="navbar navbar-fixed-top {% block navbar-variant %}navbar-default{% endblock %}">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% block branding-url %}{% url 'ui:index' %}{% endblock %}" >
                        {% block branding %}
                        <img alt="Brand" style="height: 30px; margin-right: 5px" src="{% static 'stackdio/img/logo-thumb.png' %}">
                        {% endblock %}
                    </a>
                </div>

                <div id="navbar" class="collapse navbar-collapse">
                    {% if user.is_authenticated and not hide_navbar %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="{% block stack-class %}{% endblock %}"><a href="{% url 'ui:stack-list' %}">Stacks</a></li>
                        <li class="{% block environment-class %}{% endblock %}"><a href="{% url 'ui:environment-list' %}">Environments</a></li>
                        <li class="{% block blueprint-class %}{% endblock %}"><a href="{% url 'ui:blueprint-list' %}">Blueprints</a></li>

                        {% if user.settings.advanced_view %}
                        <li class="{% block formula-class %}{% endblock %}"><a href="{% url 'ui:formula-list' %}">Formulas</a></li>
                        <li class="{% block snapshot-class %}{% endblock %}"><a href="{% url 'ui:snapshot-list' %}">Snapshots</a></li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Cloud <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="{% block account-class %}{% endblock %}"><a href="{% url 'ui:cloud-account-list' %}">Cloud Accounts</a></li>
                                <li class="{% block image-class %}{% endblock %}"><a href="{% url 'ui:cloud-image-list' %}">Cloud Images</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Admin <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="{% block user-class %}{% endblock %}"><a href="{% url 'ui:user-list' %}">Users</a></li>
                                <li class="{% block group-class %}{% endblock %}"><a href="{% url 'ui:group-list' %}">Groups</a></li>
                            </ul>
                        </li>
                        {% endif %}

                        <!-- Extra links -->
                        {% block links %}{% endblock %}

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="{% block profile-class %}{% endblock %}"><a href="{% url 'ui:user-profile' %}">Profile</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'ui:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    {% endblock navbar %}

    <!-- Any messages if they exist -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-warning stackdio-advanced-warning" role="alert">
                    <button id="advanced-warning-dismiss" type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    It looks like you don't have advanced view enabled.  If you would like to turn on advanced view, check out your
                    <a href="{% url 'ui:user-profile' %}" id="advanced-warning-button" class="alert-link">User Profile</a>.
                </div>
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- the main content of the page -->
    <div id="main-content" class="container">
        {% block content %}{% endblock %}
        <!-- Site footer -->
        <footer class="footer">
            <div class="row">
                <div class="col-xs-6">
                    <p>&copy; Digital Reasoning 2017</p>
                </div>
                <div class="col-xs-6">
                {% block api-link %}
                    <p class="text-right">stackd.io {% stackdio_version %} | <a href="{% url 'api:root' %}">api</a></p>
                {% endblock api-link %}
                </div>
            </div>
        </footer>
    </div>

    {% block scripts %}
    {# load these in by default if we're not using require - otherwise we'll override this later #}
    <!-- jQuery / bootstrap scripts -->
    <script src="{% static 'stackdio/lib/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'stackdio/lib/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'stackdio/lib/bower_components/fuelux/dist/js/fuelux.min.js' %}"></script>
    <script src="{% static 'stackdio/app/utils/mobile-fix.js' %}"></script>
    {% endblock scripts %}
{% endblock body %}
{% endif %}
</body>
</html>

stackdio/core/templates/stackdio/login.html
{% extends 'stackdio/base.html' %}
{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="jumbotron">
                <img class="img-responsive logo" src="{% static 'stackdio/img/logo.png' %}" />
                <p class="text-center">a modern cloud provisioning and deployment framework</p>

                <br>

                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-lg-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                            <form class="form" role="form" action="{% block login-url %}{% url 'ui:login' %}{% endblock %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input id="inputUsername" type="text" name="username" class="form-control" placeholder="Username" required autofocus>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" placeholder="Password" class="form-control" required>
                                    {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                            <span class="help-block"><small class="text-danger">{{ error }}</small></span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <input type="hidden" name="next" value="{{ next }}" />

                                <div class="form-group">
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}