stackdio/api/users/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import include, url
from stackdio.api.users import api
from stackdio.core import routers

user_model_router = routers.SimpleBulkRouter()
user_model_router.register(r'users',
                           api.UserModelUserPermissionsViewSet,
                           'user-model-user-permissions')
user_model_router.register(r'groups',
                           api.UserModelGroupPermissionsViewSet,
                           'user-model-group-permissions')


model_router = routers.SimpleBulkRouter()
model_router.register(r'users',
                      api.GroupModelUserPermissionsViewSet,
                      'group-model-user-permissions')
model_router.register(r'groups',
                      api.GroupModelGroupPermissionsViewSet,
                      'group-model-group-permissions')


object_router = routers.SimpleBulkRouter()
object_router.register(r'users',
                       api.GroupObjectUserPermissionsViewSet,
                       'group-object-user-permissions')
object_router.register(r'groups',
                       api.GroupObjectGroupPermissionsViewSet,
                       'group-object-group-permissions')


urlpatterns = (
    url(r'^users/$',
        api.UserListAPIView.as_view(),
        name='user-list'),

    url(r'^users/permissions/',
        include(user_model_router.urls)),

    url(r'^users/(?P<username>[\w.@+-]+)/$',
        api.UserDetailAPIView.as_view(),
        name='user-detail'),

    url(r'^users/(?P<parent_username>[\w.@+-]+)/groups/$',
        api.UserGroupListAPIView.as_view(),
        name='user-grouplist'),

    url(r'^groups/$',
        api.GroupListAPIView.as_view(),
        name='group-list'),

    url(r'^groups/permissions/',
        include(model_router.urls)),

    url(r'^groups/(?P<name>[\w.@+-]+)/$',
        api.GroupDetailAPIView.as_view(),
        name='group-detail'),

    url(r'^groups/(?P<parent_name>[\w.@+-]+)/permissions/',
        include(object_router.urls)),

    url(r'^groups/(?P<parent_name>[\w.@+-]+)/users/$',
        api.GroupUserListAPIView.as_view(),
        name='group-userlist'),

    url(r'^groups/(?P<parent_name>[\w.@+-]+)/action/$',
        api.GroupActionAPIView.as_view(),
        name='group-action'),

    url(r'^groups/(?P<parent_name>[\w.@+-]+)/channels/$',
        api.GroupChannelListAPIView.as_view(),
        name='group-channel-list'),

    url(r'^groups/(?P<parent_name>[\w.@+-]+)/channels/(?P<name>[\w.@+-]+)/$',
        api.GroupChannelDetailAPIView.as_view(),
        name='group-channel-detail'),

    url(r'^user/$',
        api.CurrentUserDetailAPIView.as_view(),
        name='currentuser-detail'),

    url(r'^user/token/$',
        api.AuthToken.as_view(),
        name='currentuser-token'),

    url(r'^user/token/reset/$',
        api.ResetAuthToken.as_view(),
        name='currentuser-token-reset'),

    url(r'^user/channels/$',
        api.CurrentUserChannelListAPIView.as_view(),
        name='currentuser-channel-list'),

    url(r'^user/channels/(?P<name>[\w.@+-]+)/$',
        api.CurrentUserChannelDetailAPIView.as_view(),
        name='currentuser-channel-detail'),

    url(r'^user/password/$',
        api.ChangePasswordAPIView.as_view(),
        name='currentuser-password'),
)

stackdio/server/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
stackdio URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from stackdio.api.urls import get_error_handler

# Enable admin interface
admin.autodiscover()

urlpatterns = (
    # Grab the core URLs.  Basically just the version endpoint.
    url(r'^', include('stackdio.core.urls', namespace='stackdio')),

    # API v1 root endpoint -- add additional URLs to urls.py in the api module.
    url(r'^api/', include('stackdio.api.urls', namespace='api')),

    # Default login/logout views. Without this you won't get the login/logout links
    # in the browsable api.
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),

    # Grab the ui URLs.  Stuff like index, login, logout, etc
    url(r'^', include('stackdio.ui.urls', namespace='ui')),

    # Admin interface
    url(r'^__private/admin/', include(admin.site.urls)),
)

# Override the default handlers
handler400 = get_error_handler(400)
handler403 = get_error_handler(403)
handler404 = get_error_handler(404)
handler500 = get_error_handler(500)

stackdio/ui/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from stackdio.core.utils import cached_url
from stackdio.ui import views
from stackdio.ui.views import accounts
from stackdio.ui.views import blueprints
from stackdio.ui.views import environments
from stackdio.ui.views import formulas
from stackdio.ui.views import images
from stackdio.ui.views import snapshots
from stackdio.ui.views import stacks
from stackdio.ui.views import users

auth_login_kwargs = {
    'template_name': 'stackdio/login.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_confirm_kwargs = {
    'post_reset_redirect': 'ui:password_reset_complete',
    'template_name': 'stackdio/auth/password_reset_confirm.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_complete_kwargs = {
    'template_name': 'stackdio/auth/password_reset_complete.html',
    'extra_context': {'hide_navbar': True},
}

urlpatterns = (
    cached_url(r'^$',
               views.RootView.as_view(),
               name='index'),

    cached_url(r'^login/$',
               auth_views.login,
               auth_login_kwargs,
               name='login',
               user_sensitive=False),

    url(r'^logout/$',
        auth_views.logout_then_login,
        name='logout'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        auth_reset_confirm_kwargs,
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        auth_reset_complete_kwargs,
        name='password_reset_complete'),

    cached_url(r'^js/main.js$',
               views.AppMainView.as_view(),
               name='js-main',
               user_sensitive=False),

    cached_url('^user/$',
               users.UserProfileView.as_view(),
               name='user-profile',
               timeout=10),

    cached_url('^user/password/$',
               users.UserPasswordChangeView.as_view(),
               name='user-password-change',
               timeout=10),

    cached_url(r'^users/$',
               users.UserListView.as_view(),
               name='user-list',
               timeout=30),

    cached_url(r'^users/create/$',
               users.UserCreateView.as_view(),
               name='user-create'),

    cached_url(r'^users/permissions/$',
               users.UserModelPermissionsView.as_view(),
               name='user-model-permissions'),

    cached_url(r'^groups/$',
               users.GroupListView.as_view(),
               name='group-list',
               timeout=30),

    cached_url(r'^groups/create/$',
               users.GroupCreateView.as_view(),
               name='group-create'),

    cached_url(r'^groups/permissions/$',
               users.GroupModelPermissionsView.as_view(),
               name='group-model-permissions'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/$',
               users.GroupDetailView.as_view(),
               name='group-detail',
               timeout=30),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/members/$',
               users.GroupMembersView.as_view(),
               name='group-members'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/permissions/$',
               users.GroupObjectPermissionsView.as_view(),
               name='group-object-permissions'),

    cached_url(r'^stacks/$',
               stacks.StackListView.as_view(),
               name='stack-list',
               timeout=30),

    cached_url(r'^stacks/create/$',
               stacks.StackCreateView.as_view(),
               name='stack-create'),

    cached_url(r'^stacks/permissions/$',
               stacks.StackModelPermissionsView.as_view(),
               name='stack-model-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/$',
               stacks.StackDetailView.as_view(),
               name='stack-detail',
               timeout=30),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/properties/$',
               stacks.StackPropertiesView.as_view(),
               name='stack-properties'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/labels/$',
               stacks.StackLabelsView.as_view(),
               name='stack-labels'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/hosts/$',
               stacks.StackHostsView.as_view(),
               name='stack-hosts'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/components/$',
               stacks.StackComponentsView.as_view(),
               name='stack-components'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/volumes/$',
               stacks.StackVolumesView.as_view(),
               name='stack-volumes'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/$',
               stacks.StackCommandsView.as_view(),
               name='stack-commands'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/(?P<command_pk>[0-9]+)/$',
               stacks.StackCommandDetailView.as_view(),
               name='stack-command-detail'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/access_rules/$',
               stacks.StackAccessRulesView.as_view(),
               name='stack-access-rules'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/formula_versions/$',
               stacks.StackFormulaVersionsView.as_view(),
               name='stack-formula-versions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/permissions/$',
               stacks.StackObjectPermissionsView.as_view(),
               name='stack-object-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/logs/$',
               stacks.StackLogsView.as_view(),
               name='stack-logs'),

    cached_url(r'^environments/$',
               environments.EnvironmentListView.as_view(),
               name='environment-list',
               timeout=30),

    cached_url(r'^environments/create/$',
               environments.EnvironmentCreateView.as_view(),
               name='environment-create'),

    cached_url(r'^environments/permissions/$',
               environments.EnvironmentModelPermissionsView.as_view(),
               name='environment-model-permissions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/$',
               environments.EnvironmentDetailView.as_view(),
               name='environment-detail',
               timeout=30),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/properties/$',
               environments.EnvironmentPropertiesView.as_view(),
               name='environment-properties'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/hosts/$',
               environments.EnvironmentHostsView.as_view(),
               name='environment-hosts'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/labels/$',
               environments.EnvironmentLabelsView.as_view(),
               name='environment-labels'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/formula_versions/$',
               environments.EnvironmentFormulaVersionsView.as_view(),
               name='environment-formula-versions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/components/$',
               environments.EnvironmentComponentsView.as_view(),
               name='environment-components'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/logs/$',
               environments.EnvironmentLogsView.as_view(),
               name='environment-logs'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/permissions/$',
               environments.EnvironmentObjectPermissionsView.as_view(),
               name='environment-object-permissions'),

    cached_url(r'^blueprints/$',
               blueprints.BlueprintListView.as_view(),
               name='blueprint-list',
               timeout=30),

    cached_url(r'^blueprints/permissions/$',
               blueprints.BlueprintModelPermissionsView.as_view(),
               name='blueprint-model-permissions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/$',
               blueprints.BlueprintDetailView.as_view(),
               name='blueprint-detail',
               timeout=30),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/properties/$',
               blueprints.BlueprintPropertiesView.as_view(),
               name='blueprint-properties'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/labels/$',
               blueprints.BlueprintLabelsView.as_view(),
               name='blueprint-labels'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/host_definitions/$',
               blueprints.BlueprintHostDefinitionsView.as_view(),
               name='blueprint-host-definitions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/formula_versions/$',
               blueprints.BlueprintFormulaVersionsView.as_view(),
               name='blueprint-formula-versions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/permissions/$',
               blueprints.BlueprintObjectPermissionsView.as_view(),
               name='blueprint-object-permissions'),

    cached_url(r'^formulas/$',
               formulas.FormulaListView.as_view(),
               name='formula-list',
               timeout=30),

    cached_url(r'^formulas/import/$',
               formulas.FormulaImportView.as_view(),
               name='formula-import'),

    cached_url(r'^formulas/permissions/$',
               formulas.FormulaModelPermissionsView.as_view(),
               name='formula-model-permissions'),

stackdio/ui/templates/users/group-create.html
{% extends 'stackdio/page.html' %}
{% load staticfiles %}

{% block title %}Create Group{% endblock %}
{% block group-class %}active{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/ladda/dist/ladda-themeless.min.css' %}">
{% endblock %}

{% block page-content %}
    <form data-bind="submit: createGroup">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group" id="name">
                    <label for="groupName">Name</label>
                    <input type="text" class="form-control" id="groupName"
                           data-bind="value: name, valueUpdate: 'keyup'">
                </div>

                <button type="submit" id="create-button" data-style="slide-left"
                        data-bind="enable: name"
                        class="btn btn-success ladda-button" style="margin-top: 10px">
                    <span class="ladda-label">Create Group</span>
                </button>
            </div>
        </div>
    </form>
{% endblock %}

stackdio/ui/templates/users/group-detail-base.html
{% extends 'stackdio/page.html' %}

{% block title %}Group Detail{% endblock %}
{% block group-class %}active{% endblock %}

{# Inject the group id into the window so we can access it in our javascript VM #}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        if (typeof window.stackdio == 'undefined') window.stackdio = {};
        window.stackdio.groupName = '{{ group.name }}';
    </script>
{% endblock %}


{% block page-content %}
    <div class="row">
        <div class="col-sm-3 col-sm-push-9">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"{% if page_id == 'detail' %} class="active"{% endif %}>
                    <a href="{% url 'ui:group-detail' name=group.name %}">Detail</a>
                </li>
                <li role="presentation"{% if page_id == 'members' %} class="active"{% endif %}>
                    <a href="{% url 'ui:group-members' name=group.name %}">Members</a>
                </li>
                {% if has_admin %}
                <li role="presentation"{% if page_id == 'permissions' %} class="active"{% endif %}>
                    <a href="{% url 'ui:group-object-permissions' name=group.name %}">Permissions</a>
                </li>
                {% endif %}
            </ul>
        </div>

        {% block detail-content %}{% endblock %}
    </div>
{% endblock %}

stackdio/ui/templates/users/group-detail.html
{% extends 'users/group-detail-base.html' %}


{% block detail-content %}
<div class="col-sm-9 col-sm-pull-3">
    <div class="row">
        <div class="col-md-6">
            <form data-bind="submit: function() { group.save(); }">
                <div id="name" class="form-group">
                    <label for="groupName">Name</label>
                    <input type="text" class="form-control" id="groupName"
                           data-bind="value: group.name, valueUpdate: 'keyup'">
                </div>

                <div class="form-group" style="margin-top: 15px">
                    {% if has_update %}
                    <button type="submit" class="btn btn-primary">Save</button>
                    {% endif %}

                    {% if has_delete %}
                    <button class="btn btn-danger" data-bind="click: function () { group.delete() }">
                        Delete
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stackdio/ui/templates/users/group-list.html
{% extends 'stackdio/page.html' %}

{% block title %}Groups{% endblock %}
{% block group-class %}active{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-md-6">
            <h2 style="margin-top: 0">Groups</h2>
            <p>Manage all of your groups here.</p>
        </div>
        <div class="col-md-6 text-right">
            {% if has_admin %}
            <!-- Only show the button if the group has permission to see it-->
            <a class="btn btn-warning" href="{% url 'ui:group-model-permissions' %}">Permissions</a>
            {% endif %}
            {% if has_create %}
                <a class="btn btn-success" href="{% url 'ui:group-create' %}">New Group</a>
            {% endif %}
        </div>
    </div>

    {% include 'stackdio/stubs/pager.html' with object_type='groups' search=True %}

    <div class="row" style="margin-top: 15px">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <!-- ko foreach: sortableFields -->
                    <th data-bind="style: {width: width}">
                        <a href="#" data-bind="text: displayName, click: function (field) { $root.changeSortKey(field) }"></a>
                        <span data-bind="visible: $root.sortKey() === name, css: {dropdown: $root.sortAsc(), dropup: !$root.sortAsc()}">
                            <span class="caret"></span>
                        </span>
                    </th>
                    <!-- /ko -->
                    <th style="width: 10%"></th>
                </tr>
                </thead>
                <tbody data-bind="foreach: sortedObjects">
                <tr class="stackdio-hidden-on-load">
                    <td>
                        <!-- ko if: $root.canDisplayDetail -->
                        <a data-bind="text: name, attr: {href: detailUrl, title: name}"></a>
                        <!-- /ko -->
                        <!-- ko ifnot: $root.canDisplayDetail -->
                        <p data-bind="text: name"></p>
                        <!-- /ko -->
                    </td>
                    <td class="text-center">
                        <a href="#" data-bind="click: $data.delete, if: !$root.permissionsMap[$data.name()] || $root.permissionsMap[$data.name()].delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

stackdio/ui/templates/users/ldap-managed.html
{% extends 'stackdio/base.html' %}

{% block title %}LDAP managed{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>This is an LDAP managed feature</h1>
        <p>You have LDAP enabled, so you may not manually create and manage users.</p>
    </div>
</div>
{% endblock %}

stackdio/ui/templates/users/user-list.html
{% extends 'stackdio/page.html' %}

{% block title %}Users{% endblock %}
{% block user-class %}active{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-md-6">
            <h2 style="margin-top: 0">Users</h2>
            <p>Manage all of your users here.</p>
        </div>
        <div class="col-md-6 text-right">
            {% if not ldap_enabled and has_admin %}
            <!-- Only show the button if the user has permission to see it-->
            <a class="btn btn-warning" href="{% url 'ui:user-model-permissions' %}">Permissions</a>
            {% endif %}
            {% if not ldap_enabled and has_create %}
                <a class="btn btn-success" href="{% url 'ui:user-create' %}">New User</a>
            {% endif %}
        </div>
    </div>

    {% include 'stackdio/stubs/pager.html' with object_type='users' search=True %}

    <div class="row" style="margin-top: 15px">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <!-- ko foreach: sortableFields -->
                    <th data-bind="style: {width: width}">
                        <a href="#" data-bind="text: displayName, click: function (field) { $root.changeSortKey(field) }"></a>
                        <span data-bind="visible: $root.sortKey() === name, css: {dropdown: $root.sortAsc(), dropup: !$root.sortAsc()}">
                            <span class="caret"></span>
                        </span>
                    </th>
                    <!-- /ko -->
                </tr>
                </thead>
                <tbody data-bind="foreach: sortedObjects">
                <tr class="stackdio-hidden-on-load">
                    <td data-bind="text: username"></td>
                    <td data-bind="text: firstName"></td>
                    <td data-bind="text: lastName"></td>
                    <td data-bind="text: email"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

stackdio/ui/templates/users/user-profile.html
{% extends 'stackdio/page.html' %}

{% block title %}User Profile{% endblock %}
{% block profile-class %}active{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
    if (typeof window.stackdio == 'undefined') window.stackdio = {};
    window.stackdio.ldapEnabled = {{ ldap | lower }};
    </script>
{% endblock %}

{% block page-content %}
    <form data-bind="submit: function () { user.save() }">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group" id="username">
                    <label for="userUsername">Username</label>
                    {% if ldap %}
                    <p class="form-control-static" id="userUsername"
                           data-bind="text: user.username"></p>
                    {% else %}
                    <input type="text" class="form-control" id="userUsername"
                           data-bind="value: user.username, valueUpdate: 'keyup'">
                    {% endif %}
                </div>
                <div class="form-group" id="first_name">
                    <label for="userFirstName">First Name</label>
                    {% if ldap %}
                    <p class="form-control-static" id="userFirstName"
                           data-bind="text: user.firstName"></p>
                    {% else %}
                    <input type="text" class="form-control" id="userFirstName"
                           data-bind="value: user.firstName, valueUpdate: 'keyup'">
                    {% endif %}
                </div>
                <div class="form-group" id="last_name">
                    <label for="userLastName">Last Name</label>
                    {% if ldap %}
                    <p class="form-control-static" id="userLastName"
                           data-bind="text: user.lastName"></p>
                    {% else %}
                    <input type="text" class="form-control" id="userLastName"
                           data-bind="value: user.lastName, valueUpdate: 'keyup'">
                    {% endif %}
                </div>
                <div class="form-group" id="email">
                    <label for="userEmail">Email Address</label>
                    {% if ldap %}
                    <p class="form-control-static" id="userEmail"
                           data-bind="text: user.email"></p>
                    {% else %}
                    <input type="text" class="form-control" id="userEmail"
                           data-bind="value: user.email, valueUpdate: 'keyup'">
                    {% endif %}
                </div>
                <div class="form-group" id="last_login">
                    <label for="userLastLogin">Last Login</label>
                    <p class="form-control-static" id="userLastLogin"
                       data-bind="text: user.lastLogin().calendar()"></p>
                </div>

                <div class="form-group" id="token">
                    <label for="userToken">API Token</label>
                    <p class="form-control-static" id="userToken">
                        <a href="" data-bind="visible: !userTokenShown(), click: showUserToken">Show API Token</a>
                        <span data-bind="visible: userTokenShown">
                            <code data-bind="text: userToken"></code>
                            <br>
                            <br>
                            <a href="" data-toggle="modal" data-target="#token-help">API Token Help</a>
                            <br>
                            <br>
                            <a href="" data-bind="click: resetUserToken">Reset API Token</a>
                        </span>
                    </p>
                </div>

                <button type="submit" class="btn btn-primary">Save</button>
                {% if not ldap %}
                <a class="btn btn-info" href="{% url 'ui:user-password-change' %}">Change Password</a>
                {% endif %}
            </div>

            <div class="col-md-6">
                <div class="form-group" id="public_key">
                    <label for="userPublicKey">Public Key</label>
                    <textarea class="form-control" id="userPublicKey" rows="10"
                              data-bind="value: user.publicKey, valueUpdate: 'keyup'">
                    </textarea>
                </div>
                <div id="advanced_view">
                    <div class="checkbox">
                        <label class="checkbox-custom" data-initialize="checkbox">
                            <input class="sr-only" type="checkbox" data-bind="checked: user.advanced">
                            <span class="checkbox-label">Advanced View</span>
                        </label>
                    </div>
                </div>

                <br>

                <label>Member of these groups:</label>

                <ul data-bind="foreach: user.groups">
                    <li data-bind="text: name"></li>
                </ul>
            </div>
        </div>
    </form>

    <div class="modal fade" id="token-help" tabindex="-1" role="dialog" aria-labelledby="token-help-label">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="token-help-label">How to use the API Token</h4>
                </div>
                <div class="modal-body">
                    <p>To use your API token, you must set the <code>Authorization</code> HTTP header, prefixed by the string literal &quot;Token&quot;.  For example:</p>
                    <pre>Authorization: Token <span data-bind="text: userToken"></span></pre>
                    <p>Try running this example curl command:  (It already contains <strong>your</strong> token)</p>
                    <pre>curl -X GET <span data-bind="text: apiRootUrl"></span> \<br>  -H 'Authorization: Token <span data-bind="text: userToken"></span>'</pre>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}