stackdio/api/blueprints/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import include, url
from stackdio.api.blueprints import api
from stackdio.core import routers

model_router = routers.SimpleBulkRouter()
model_router.register(r'users',
                      api.BlueprintModelUserPermissionsViewSet,
                      'blueprint-model-user-permissions')
model_router.register(r'groups',
                      api.BlueprintModelGroupPermissionsViewSet,
                      'blueprint-model-group-permissions')


object_router = routers.SimpleBulkRouter()
object_router.register(r'users',
                       api.BlueprintObjectUserPermissionsViewSet,
                       'blueprint-object-user-permissions')
object_router.register(r'groups',
                       api.BlueprintObjectGroupPermissionsViewSet,
                       'blueprint-object-group-permissions')


urlpatterns = (
    url(r'^$',
        api.BlueprintListAPIView.as_view(),
        name='blueprint-list'),

    url(r'^permissions/',
        include(model_router.urls)),

    url(r'^(?P<pk>[0-9]+)/$',
        api.BlueprintDetailAPIView.as_view(),
        name='blueprint-detail'),

    url(r'^(?P<pk>[0-9]+)/export/$',
        api.BlueprintExportAPIView.as_view(),
        name='blueprint-export'),

    url(r'^(?P<pk>[0-9]+)/properties/$',
        api.BlueprintPropertiesAPIView.as_view(),
        name='blueprint-properties'),

    url(r'^(?P<parent_pk>[0-9]+)/host_definitions/$',
        api.BlueprintHostDefinitionListAPIView.as_view(),
        name='blueprint-host-definition-list'),

    url(r'^(?P<parent_pk>[0-9]+)/host_definitions/(?P<pk>[0-9]+)/$',
        api.BlueprintHostDefinitionDetailAPIView.as_view(),
        name='blueprint-host-definition-detail'),

    url(r'^(?P<parent_pk>[0-9]+)/formula_versions/$',
        api.BlueprintFormulaVersionsAPIView.as_view(),
        name='blueprint-formula-versions'),

    url(r'^(?P<parent_pk>[0-9]+)/labels/$',
        api.BlueprintLabelListAPIView.as_view(),
        name='blueprint-label-list'),

    url(r'^(?P<parent_pk>[0-9]+)/labels/(?P<label_name>[\w.@+-]+)/$',
        api.BlueprintLabelDetailAPIView.as_view(),
        name='blueprint-label-detail'),

    url(r'^(?P<parent_pk>[0-9]+)/permissions/',
        include(object_router.urls)),
)

stackdio/server/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
stackdio URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from stackdio.api.urls import get_error_handler

# Enable admin interface
admin.autodiscover()

urlpatterns = (
    # Grab the core URLs.  Basically just the version endpoint.
    url(r'^', include('stackdio.core.urls', namespace='stackdio')),

    # API v1 root endpoint -- add additional URLs to urls.py in the api module.
    url(r'^api/', include('stackdio.api.urls', namespace='api')),

    # Default login/logout views. Without this you won't get the login/logout links
    # in the browsable api.
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),

    # Grab the ui URLs.  Stuff like index, login, logout, etc
    url(r'^', include('stackdio.ui.urls', namespace='ui')),

    # Admin interface
    url(r'^__private/admin/', include(admin.site.urls)),
)

# Override the default handlers
handler400 = get_error_handler(400)
handler403 = get_error_handler(403)
handler404 = get_error_handler(404)
handler500 = get_error_handler(500)

stackdio/ui/urls.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from stackdio.core.utils import cached_url
from stackdio.ui import views
from stackdio.ui.views import accounts
from stackdio.ui.views import blueprints
from stackdio.ui.views import environments
from stackdio.ui.views import formulas
from stackdio.ui.views import images
from stackdio.ui.views import snapshots
from stackdio.ui.views import stacks
from stackdio.ui.views import users

auth_login_kwargs = {
    'template_name': 'stackdio/login.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_confirm_kwargs = {
    'post_reset_redirect': 'ui:password_reset_complete',
    'template_name': 'stackdio/auth/password_reset_confirm.html',
    'extra_context': {'hide_navbar': True},
}

auth_reset_complete_kwargs = {
    'template_name': 'stackdio/auth/password_reset_complete.html',
    'extra_context': {'hide_navbar': True},
}

urlpatterns = (
    cached_url(r'^$',
               views.RootView.as_view(),
               name='index'),

    cached_url(r'^login/$',
               auth_views.login,
               auth_login_kwargs,
               name='login',
               user_sensitive=False),

    url(r'^logout/$',
        auth_views.logout_then_login,
        name='logout'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        auth_reset_confirm_kwargs,
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        auth_reset_complete_kwargs,
        name='password_reset_complete'),

    cached_url(r'^js/main.js$',
               views.AppMainView.as_view(),
               name='js-main',
               user_sensitive=False),

    cached_url('^user/$',
               users.UserProfileView.as_view(),
               name='user-profile',
               timeout=10),

    cached_url('^user/password/$',
               users.UserPasswordChangeView.as_view(),
               name='user-password-change',
               timeout=10),

    cached_url(r'^users/$',
               users.UserListView.as_view(),
               name='user-list',
               timeout=30),

    cached_url(r'^users/create/$',
               users.UserCreateView.as_view(),
               name='user-create'),

    cached_url(r'^users/permissions/$',
               users.UserModelPermissionsView.as_view(),
               name='user-model-permissions'),

    cached_url(r'^groups/$',
               users.GroupListView.as_view(),
               name='group-list',
               timeout=30),

    cached_url(r'^groups/create/$',
               users.GroupCreateView.as_view(),
               name='group-create'),

    cached_url(r'^groups/permissions/$',
               users.GroupModelPermissionsView.as_view(),
               name='group-model-permissions'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/$',
               users.GroupDetailView.as_view(),
               name='group-detail',
               timeout=30),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/members/$',
               users.GroupMembersView.as_view(),
               name='group-members'),

    cached_url(r'^groups/(?P<name>[\w.@+-]+)/permissions/$',
               users.GroupObjectPermissionsView.as_view(),
               name='group-object-permissions'),

    cached_url(r'^stacks/$',
               stacks.StackListView.as_view(),
               name='stack-list',
               timeout=30),

    cached_url(r'^stacks/create/$',
               stacks.StackCreateView.as_view(),
               name='stack-create'),

    cached_url(r'^stacks/permissions/$',
               stacks.StackModelPermissionsView.as_view(),
               name='stack-model-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/$',
               stacks.StackDetailView.as_view(),
               name='stack-detail',
               timeout=30),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/properties/$',
               stacks.StackPropertiesView.as_view(),
               name='stack-properties'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/labels/$',
               stacks.StackLabelsView.as_view(),
               name='stack-labels'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/hosts/$',
               stacks.StackHostsView.as_view(),
               name='stack-hosts'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/components/$',
               stacks.StackComponentsView.as_view(),
               name='stack-components'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/volumes/$',
               stacks.StackVolumesView.as_view(),
               name='stack-volumes'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/$',
               stacks.StackCommandsView.as_view(),
               name='stack-commands'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/commands/(?P<command_pk>[0-9]+)/$',
               stacks.StackCommandDetailView.as_view(),
               name='stack-command-detail'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/access_rules/$',
               stacks.StackAccessRulesView.as_view(),
               name='stack-access-rules'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/formula_versions/$',
               stacks.StackFormulaVersionsView.as_view(),
               name='stack-formula-versions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/permissions/$',
               stacks.StackObjectPermissionsView.as_view(),
               name='stack-object-permissions'),

    cached_url(r'^stacks/(?P<pk>[0-9]+)/logs/$',
               stacks.StackLogsView.as_view(),
               name='stack-logs'),

    cached_url(r'^environments/$',
               environments.EnvironmentListView.as_view(),
               name='environment-list',
               timeout=30),

    cached_url(r'^environments/create/$',
               environments.EnvironmentCreateView.as_view(),
               name='environment-create'),

    cached_url(r'^environments/permissions/$',
               environments.EnvironmentModelPermissionsView.as_view(),
               name='environment-model-permissions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/$',
               environments.EnvironmentDetailView.as_view(),
               name='environment-detail',
               timeout=30),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/properties/$',
               environments.EnvironmentPropertiesView.as_view(),
               name='environment-properties'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/hosts/$',
               environments.EnvironmentHostsView.as_view(),
               name='environment-hosts'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/labels/$',
               environments.EnvironmentLabelsView.as_view(),
               name='environment-labels'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/formula_versions/$',
               environments.EnvironmentFormulaVersionsView.as_view(),
               name='environment-formula-versions'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/components/$',
               environments.EnvironmentComponentsView.as_view(),
               name='environment-components'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/logs/$',
               environments.EnvironmentLogsView.as_view(),
               name='environment-logs'),

    cached_url(r'^environments/(?P<name>[a-z0-9\-_]+)/permissions/$',
               environments.EnvironmentObjectPermissionsView.as_view(),
               name='environment-object-permissions'),

    cached_url(r'^blueprints/$',
               blueprints.BlueprintListView.as_view(),
               name='blueprint-list',
               timeout=30),

    cached_url(r'^blueprints/permissions/$',
               blueprints.BlueprintModelPermissionsView.as_view(),
               name='blueprint-model-permissions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/$',
               blueprints.BlueprintDetailView.as_view(),
               name='blueprint-detail',
               timeout=30),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/properties/$',
               blueprints.BlueprintPropertiesView.as_view(),
               name='blueprint-properties'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/labels/$',
               blueprints.BlueprintLabelsView.as_view(),
               name='blueprint-labels'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/host_definitions/$',
               blueprints.BlueprintHostDefinitionsView.as_view(),
               name='blueprint-host-definitions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/formula_versions/$',
               blueprints.BlueprintFormulaVersionsView.as_view(),
               name='blueprint-formula-versions'),

    cached_url(r'^blueprints/(?P<pk>[0-9]+)/permissions/$',
               blueprints.BlueprintObjectPermissionsView.as_view(),
               name='blueprint-object-permissions'),

    cached_url(r'^formulas/$',
               formulas.FormulaListView.as_view(),
               name='formula-list',
               timeout=30),

    cached_url(r'^formulas/import/$',
               formulas.FormulaImportView.as_view(),
               name='formula-import'),

    cached_url(r'^formulas/permissions/$',
               formulas.FormulaModelPermissionsView.as_view(),
               name='formula-model-permissions'),

stackdio/api/blueprints/admin.py
# -*- coding: utf-8 -*-

# Copyright 2017,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import unicode_literals

from django.contrib import admin
from guardian.admin import GuardedModelAdmin
from stackdio.api.blueprints import models


class BlueprintAdmin(GuardedModelAdmin):
    list_display = [
        'title',
        'slug',
        'host_definition_count',
        'created',
        'modified',
    ]


admin.site.register(models.Blueprint, BlueprintAdmin)


class BlueprintHostDefinitionAdmin(GuardedModelAdmin):
    list_display = [
        'hostname_template',
        'blueprint',
        'cloud_image',
        'count',
        'size',
        'zone',
        'subnet_id',
        'formula_components_count',
    ]


admin.site.register(models.BlueprintHostDefinition,
                    BlueprintHostDefinitionAdmin)


class BlueprintAccessRuleAdmin(GuardedModelAdmin):
    list_display = [
        'host',
        'protocol',
        'from_port',
        'to_port',
        'rule',
    ]


admin.site.register(models.BlueprintAccessRule, BlueprintAccessRuleAdmin)

stackdio/blueprints/tests.py
# -*- coding: utf-8 -*-

# Copyright 2014,  Digital Reasoning
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

stackdio/ui/templates/blueprints/blueprint-detail-base.html
{% extends 'stackdio/page.html' %}

{% block title %}Blueprint Detail{% endblock %}
{% block blueprint-class %}active{% endblock %}

{# Inject the blueprint id into the window so we can access it in our javascript VM #}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        if (typeof window.stackdio == 'undefined') window.stackdio = {};
        window.stackdio.blueprintId = {{ blueprint.id }};
        window.stackdio.blueprintTitle = '{{ blueprint.title }}';
        {% if has_update != None %}
        window.stackdio.hasUpdatePerm = {{ has_update | lower }};
        {% endif %}
    </script>
{% endblock %}


{% block page-content %}
    <div class="row">
        <div class="col-sm-3 col-sm-push-9">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation"{% if page_id == 'detail' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-detail' pk=blueprint.id %}">Detail</a>
                </li>
                <li role="presentation"{% if page_id == 'properties' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-properties' pk=blueprint.id %}">Properties</a>
                </li>
                <li role="presentation"{% if page_id == 'labels' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-labels' pk=blueprint.id %}">Labels</a>
                </li>
                <li role="presentation"{% if page_id == 'host-definitions' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-host-definitions' pk=blueprint.id %}">Host Definitions</a>
                </li>
{#                <li role="presentation"{% if page_id == 'access-rules' %} class="active"{% endif %}>#}
{#                    <a href="">Access Rules</a>#}
{#                </li>#}
                <li role="presentation"{% if page_id == 'formula-versions' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-formula-versions' pk=blueprint.id %}">Formula Versions</a>
                </li>
                {% if has_admin %}
                <li role="presentation"{% if page_id == 'permissions' %} class="active"{% endif %}>
                    <a href="{% url 'ui:blueprint-object-permissions' pk=blueprint.id %}">Permissions</a>
                </li>
                {% endif %}
            </ul>
        </div>

        {% block detail-content %}{% endblock %}
    </div>
{% endblock %}

stackdio/ui/templates/blueprints/blueprint-detail.html
{% extends 'blueprints/blueprint-detail-base.html' %}


{% block detail-content %}
<div class="col-sm-6 col-sm-pull-3">
    <div class="row">
        <div class="col-md-12">
            <form data-bind="submit: function() { blueprint.save(); }">
                <div id="title" class="form-group">
                    <label for="blueprintTitle">Title</label>
                    <input type="text" class="form-control" id="blueprintTitle"
                           data-bind="value: blueprint.title, valueUpdate: 'keyup'">
                </div>
                <div id="description" class="form-group">
                    <label for="blueprintDescription">Description</label>
                    <input type="text" class="form-control" id="blueprintDescription"
                           data-bind="value: blueprint.description, valueUpdate: 'keyup'">
                </div>
                <div id="create_users">
                    <div class="checkbox">
                        <label class="checkbox-custom" data-initialize="checkbox">
                            <input class="sr-only" type="checkbox"
                                   data-bind="checked: blueprint.createUsers">
                            <span class="checkbox-label">Create Users</span>
                        </label>
                    </div>
                </div>
                <div class="form-group" style="margin-top: 15px">
                    {% if has_update %}
                    <button type="submit" class="btn btn-primary">Save</button>
                    {% endif %}

                    {% if has_delete %}
                    <button class="btn btn-danger" data-bind="click: function () { blueprint.delete() }">
                        Delete
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                    {% endif %}

                    <a href="{% url 'ui:stack-create' %}?blueprint={{ blueprint.id }}" class="btn btn-info">Launch a Stack</a>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="col-sm-3 col-sm-pull-3"></div>
{% endblock %}

stackdio/ui/templates/blueprints/blueprint-formula-versions.html
{% extends 'blueprints/blueprint-detail-base.html' %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stackdio/lib/bower_components/select2-bootstrap-theme/dist/select2-bootstrap.min.css' %}">
{% endblock %}

{% block detail-content %}
    <div class="col-sm-9 col-sm-pull-3">
        {% include 'stackdio/stubs/pager.html' with object_type='formula versions' search=True %}

        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        {% include 'stackdio/stubs/table-sort-header.html' %}
                    </tr>
                    </thead>
                    <tbody>
                    <!-- ko foreach: sortedObjects -->
                    <tr class="stackdio-hidden-on-load" data-bind="visible: $root.versionsReady">
                        <td data-bind="text: formula"></td>
                        {% if has_update %}
                        <td>
                            <select style="width: 100%" class="hidden-formula-versions" data-bind="attr: {id: formulaHtmlId}"></select>
                        </td>
                        {% else %}
                        <td data-bind="text: version"></td>
                        {% endif %}
                    </tr>
                    <!-- /ko -->
                    </tbody>
                </table>
            </div>
        </div>

        {% if has_update %}
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary" data-bind="click: function () { saveVersions() }">Save</button>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

stackdio/ui/templates/blueprints/blueprint-list.html
{% extends 'stackdio/page.html' %}

{% block title %}Blueprints{% endblock %}
{% block blueprint-class %}active{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-md-6">
            <h2 style="margin-top: 0">Blueprints</h2>
            <p>Manage all of your blueprints here.</p>
        </div>
        <div class="col-md-6 text-right">
            {% if has_admin %}
            <!-- Only show the button if the user has permission to see it-->
            <a class="btn btn-warning" href="{% url 'ui:blueprint-model-permissions' %}">Permissions</a>
            {% endif %}
{#            {% if has_create %}#}
{#                <a class="btn btn-success" href="{% url 'ui:blueprint-create' %}">New Blueprint</a>#}
{#            {% endif %}#}
        </div>
    </div>

    {% include 'stackdio/stubs/pager.html' with object_type='blueprints' search=True %}

    <div class="row" style="margin-top: 15px">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <!-- ko foreach: sortableFields -->
                    <th data-bind="style: {width: width}">
                        <a href="#" data-bind="text: displayName, click: function (field) { $root.changeSortKey(field) }"></a>
                        <span data-bind="visible: $root.sortKey() === name, css: {dropdown: $root.sortAsc(), dropup: !$root.sortAsc()}">
                            <span class="caret"></span>
                        </span>
                    </th>
                    <!-- /ko -->
                    <th style="width: 5%"></th>
                    <th style="width: 5%"></th>
                </tr>
                </thead>
                <tbody data-bind="foreach: sortedObjects">
                <tr class="stackdio-hidden-on-load">
                    <td>
                        <!-- ko if: $root.canDisplayDetail -->
                        <a data-bind="text: title, attr: {href: detailUrl, title: title}"></a>
                        <!-- /ko -->
                        <!-- ko ifnot: $root.canDisplayDetail -->
                        <p data-bind="text: title"></p>
                        <!-- /ko -->
                    </td>
                    <td data-bind="text: description"></td>
                    <td data-bind="foreach: labelList">
                        <!-- ko if: value -->
                        <span class="label label-default" data-bind="text: key + ':' + value"></span>
                        <!-- /ko -->
                        <!-- ko ifnot: value -->
                        <span class="label label-default" data-bind="text: key"></span>
                        <!-- /ko -->
                    </td>
                    <td data-bind="text: stackCount"></td>
                    <td class="text-center">
                        <a href="#" class="btn btn-xs btn-info" data-bind="click: $data.launch">
                            Launch
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="#" data-bind="click: $data.delete, if: !$root.permissionsMap[$data.id] || $root.permissionsMap[$data.id].delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

stackdio/ui/templates/blueprints/blueprint-object-permissions.html
{% extends 'blueprints/blueprint-detail-base.html' %}

{% block title %}{{ object_type }} Permissions{% endblock %}

{# Inject the blueprint id into the window so we can access it in our javascript VM #}
{% if object_id %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        if (typeof window.stackdio == 'undefined') window.stackdio = {};
        window.stackdio.objectId = {{ object_id }};
    </script>
{% endblock %}
{% endif %}

{% block detail-content %}
<div class="col-sm-9 col-sm-pull-3">
    {% include 'stackdio/stubs/permissions-table.html' with user_or_group='user' %}

    {% include 'stackdio/stubs/permissions-table.html' with user_or_group='group' %}
</div>
{% endblock %}

stackdio/ui/templates/blueprints/blueprint-properties.html
{% extends 'blueprints/blueprint-detail-base.html' %}
{% load staticfiles %}


{% block detail-content %}
<div class="col-sm-9 col-sm-pull-3">
    <div class="row">
        <div class="col-md-12">
            <form data-bind="submit: saveProperties">
                <div class="form-group" id="properties">
                    <label for="blueprintProperties">Properties</label>

                    {% if has_update %}
                    <textarea class="form-control" id="blueprintProperties" rows="25"
                              data-bind="value: propertiesJSON, valueUpdate: 'keyup'"></textarea>
                    {% else %}
                    <pre data-bind="text: propertiesJSON"></pre>
                    {% endif %}
                </div>

                {% if has_update %}
                <button type="submit" class="btn btn-success">Save</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}